package com.lxf.mapper;

import org.apache.ibatis.annotations.Mapper;

import java.util.List;

/**
 * Created by lixianfeng on 2018/6/12.
 */
@Mapper
public interface BaseMapper<T> {
    List<T> list(T t);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Tue Jun 12 17:12:11 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Tue Jun 12 17:12:11 CST 2018
     */
    int insert(T record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Tue Jun 12 17:12:11 CST 2018
     */
    int insertSelective(T record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Tue Jun 12 17:12:11 CST 2018
     */
    T selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Tue Jun 12 17:12:11 CST 2018
     */
    int updateByPrimaryKeySelective(T record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Tue Jun 12 17:12:11 CST 2018
     */
    int updateByPrimaryKey(T record);
}
