package com.lxf.model;

import java.util.Date;

public class SysUser extends BaseModel{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.id
     *
     * @mbg.generated Tue Jun 12 17:12:11 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.password
     *
     * @mbg.generated Tue Jun 12 17:12:11 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.last_login
     *
     * @mbg.generated Tue Jun 12 17:12:11 CST 2018
     */
    private Date lastLogin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.is_superuser
     *
     * @mbg.generated Tue Jun 12 17:12:11 CST 2018
     */
    private String isSuperuser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.username
     *
     * @mbg.generated Tue Jun 12 17:12:11 CST 2018
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.first_name
     *
     * @mbg.generated Tue Jun 12 17:12:11 CST 2018
     */
    private String firstName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.last_name
     *
     * @mbg.generated Tue Jun 12 17:12:11 CST 2018
     */
    private String lastName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.email
     *
     * @mbg.generated Tue Jun 12 17:12:11 CST 2018
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.regist_type
     *
     * @mbg.generated Tue Jun 12 17:12:11 CST 2018
     */
    private String registType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.status
     *
     * @mbg.generated Tue Jun 12 17:12:11 CST 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.date_joined
     *
     * @mbg.generated Tue Jun 12 17:12:11 CST 2018
     */
    private Date dateJoined;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.type
     *
     * @mbg.generated Tue Jun 12 17:12:11 CST 2018
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.new_password
     *
     * @mbg.generated Tue Jun 12 17:12:11 CST 2018
     */
    private String newPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.realname
     *
     * @mbg.generated Tue Jun 12 17:12:11 CST 2018
     */
    private String realname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.last_login_ip
     *
     * @mbg.generated Tue Jun 12 17:12:11 CST 2018
     */
    private String lastLoginIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.login_count
     *
     * @mbg.generated Tue Jun 12 17:12:11 CST 2018
     */
    private Integer loginCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.delete_flag
     *
     * @mbg.generated Tue Jun 12 17:12:11 CST 2018
     */
    private Integer deleteFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.nick_name
     *
     * @mbg.generated Tue Jun 12 17:12:11 CST 2018
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.fake_flag
     *
     * @mbg.generated Tue Jun 12 17:12:11 CST 2018
     */
    private Integer fakeFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.default_password
     *
     * @mbg.generated Tue Jun 12 17:12:11 CST 2018
     */
    private String defaultPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.phone
     *
     * @mbg.generated Tue Jun 12 17:12:11 CST 2018
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.org_id
     *
     * @mbg.generated Tue Jun 12 17:12:11 CST 2018
     */
    private Long orgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.ins_officer_id
     *
     * @mbg.generated Tue Jun 12 17:12:11 CST 2018
     */
    private Long insOfficerId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.id
     *
     * @return the value of sys_user.id
     *
     * @mbg.generated Tue Jun 12 17:12:11 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.id
     *
     * @param id the value for sys_user.id
     *
     * @mbg.generated Tue Jun 12 17:12:11 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.password
     *
     * @return the value of sys_user.password
     *
     * @mbg.generated Tue Jun 12 17:12:11 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.password
     *
     * @param password the value for sys_user.password
     *
     * @mbg.generated Tue Jun 12 17:12:11 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.last_login
     *
     * @return the value of sys_user.last_login
     *
     * @mbg.generated Tue Jun 12 17:12:11 CST 2018
     */
    public Date getLastLogin() {
        return lastLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.last_login
     *
     * @param lastLogin the value for sys_user.last_login
     *
     * @mbg.generated Tue Jun 12 17:12:11 CST 2018
     */
    public void setLastLogin(Date lastLogin) {
        this.lastLogin = lastLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.is_superuser
     *
     * @return the value of sys_user.is_superuser
     *
     * @mbg.generated Tue Jun 12 17:12:11 CST 2018
     */
    public String getIsSuperuser() {
        return isSuperuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.is_superuser
     *
     * @param isSuperuser the value for sys_user.is_superuser
     *
     * @mbg.generated Tue Jun 12 17:12:11 CST 2018
     */
    public void setIsSuperuser(String isSuperuser) {
        this.isSuperuser = isSuperuser == null ? null : isSuperuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.username
     *
     * @return the value of sys_user.username
     *
     * @mbg.generated Tue Jun 12 17:12:11 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.username
     *
     * @param username the value for sys_user.username
     *
     * @mbg.generated Tue Jun 12 17:12:11 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.first_name
     *
     * @return the value of sys_user.first_name
     *
     * @mbg.generated Tue Jun 12 17:12:11 CST 2018
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.first_name
     *
     * @param firstName the value for sys_user.first_name
     *
     * @mbg.generated Tue Jun 12 17:12:11 CST 2018
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName == null ? null : firstName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.last_name
     *
     * @return the value of sys_user.last_name
     *
     * @mbg.generated Tue Jun 12 17:12:11 CST 2018
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.last_name
     *
     * @param lastName the value for sys_user.last_name
     *
     * @mbg.generated Tue Jun 12 17:12:11 CST 2018
     */
    public void setLastName(String lastName) {
        this.lastName = lastName == null ? null : lastName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.email
     *
     * @return the value of sys_user.email
     *
     * @mbg.generated Tue Jun 12 17:12:11 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.email
     *
     * @param email the value for sys_user.email
     *
     * @mbg.generated Tue Jun 12 17:12:11 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.regist_type
     *
     * @return the value of sys_user.regist_type
     *
     * @mbg.generated Tue Jun 12 17:12:11 CST 2018
     */
    public String getRegistType() {
        return registType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.regist_type
     *
     * @param registType the value for sys_user.regist_type
     *
     * @mbg.generated Tue Jun 12 17:12:11 CST 2018
     */
    public void setRegistType(String registType) {
        this.registType = registType == null ? null : registType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.status
     *
     * @return the value of sys_user.status
     *
     * @mbg.generated Tue Jun 12 17:12:11 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.status
     *
     * @param status the value for sys_user.status
     *
     * @mbg.generated Tue Jun 12 17:12:11 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.date_joined
     *
     * @return the value of sys_user.date_joined
     *
     * @mbg.generated Tue Jun 12 17:12:11 CST 2018
     */
    public Date getDateJoined() {
        return dateJoined;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.date_joined
     *
     * @param dateJoined the value for sys_user.date_joined
     *
     * @mbg.generated Tue Jun 12 17:12:11 CST 2018
     */
    public void setDateJoined(Date dateJoined) {
        this.dateJoined = dateJoined;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.type
     *
     * @return the value of sys_user.type
     *
     * @mbg.generated Tue Jun 12 17:12:11 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.type
     *
     * @param type the value for sys_user.type
     *
     * @mbg.generated Tue Jun 12 17:12:11 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.new_password
     *
     * @return the value of sys_user.new_password
     *
     * @mbg.generated Tue Jun 12 17:12:11 CST 2018
     */
    public String getNewPassword() {
        return newPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.new_password
     *
     * @param newPassword the value for sys_user.new_password
     *
     * @mbg.generated Tue Jun 12 17:12:11 CST 2018
     */
    public void setNewPassword(String newPassword) {
        this.newPassword = newPassword == null ? null : newPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.realname
     *
     * @return the value of sys_user.realname
     *
     * @mbg.generated Tue Jun 12 17:12:11 CST 2018
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.realname
     *
     * @param realname the value for sys_user.realname
     *
     * @mbg.generated Tue Jun 12 17:12:11 CST 2018
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.last_login_ip
     *
     * @return the value of sys_user.last_login_ip
     *
     * @mbg.generated Tue Jun 12 17:12:11 CST 2018
     */
    public String getLastLoginIp() {
        return lastLoginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.last_login_ip
     *
     * @param lastLoginIp the value for sys_user.last_login_ip
     *
     * @mbg.generated Tue Jun 12 17:12:11 CST 2018
     */
    public void setLastLoginIp(String lastLoginIp) {
        this.lastLoginIp = lastLoginIp == null ? null : lastLoginIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.login_count
     *
     * @return the value of sys_user.login_count
     *
     * @mbg.generated Tue Jun 12 17:12:11 CST 2018
     */
    public Integer getLoginCount() {
        return loginCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.login_count
     *
     * @param loginCount the value for sys_user.login_count
     *
     * @mbg.generated Tue Jun 12 17:12:11 CST 2018
     */
    public void setLoginCount(Integer loginCount) {
        this.loginCount = loginCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.delete_flag
     *
     * @return the value of sys_user.delete_flag
     *
     * @mbg.generated Tue Jun 12 17:12:11 CST 2018
     */
    public Integer getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.delete_flag
     *
     * @param deleteFlag the value for sys_user.delete_flag
     *
     * @mbg.generated Tue Jun 12 17:12:11 CST 2018
     */
    public void setDeleteFlag(Integer deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.nick_name
     *
     * @return the value of sys_user.nick_name
     *
     * @mbg.generated Tue Jun 12 17:12:11 CST 2018
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.nick_name
     *
     * @param nickName the value for sys_user.nick_name
     *
     * @mbg.generated Tue Jun 12 17:12:11 CST 2018
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.fake_flag
     *
     * @return the value of sys_user.fake_flag
     *
     * @mbg.generated Tue Jun 12 17:12:11 CST 2018
     */
    public Integer getFakeFlag() {
        return fakeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.fake_flag
     *
     * @param fakeFlag the value for sys_user.fake_flag
     *
     * @mbg.generated Tue Jun 12 17:12:11 CST 2018
     */
    public void setFakeFlag(Integer fakeFlag) {
        this.fakeFlag = fakeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.default_password
     *
     * @return the value of sys_user.default_password
     *
     * @mbg.generated Tue Jun 12 17:12:11 CST 2018
     */
    public String getDefaultPassword() {
        return defaultPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.default_password
     *
     * @param defaultPassword the value for sys_user.default_password
     *
     * @mbg.generated Tue Jun 12 17:12:11 CST 2018
     */
    public void setDefaultPassword(String defaultPassword) {
        this.defaultPassword = defaultPassword == null ? null : defaultPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.phone
     *
     * @return the value of sys_user.phone
     *
     * @mbg.generated Tue Jun 12 17:12:11 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.phone
     *
     * @param phone the value for sys_user.phone
     *
     * @mbg.generated Tue Jun 12 17:12:11 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.org_id
     *
     * @return the value of sys_user.org_id
     *
     * @mbg.generated Tue Jun 12 17:12:11 CST 2018
     */
    public Long getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.org_id
     *
     * @param orgId the value for sys_user.org_id
     *
     * @mbg.generated Tue Jun 12 17:12:11 CST 2018
     */
    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.ins_officer_id
     *
     * @return the value of sys_user.ins_officer_id
     *
     * @mbg.generated Tue Jun 12 17:12:11 CST 2018
     */
    public Long getInsOfficerId() {
        return insOfficerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.ins_officer_id
     *
     * @param insOfficerId the value for sys_user.ins_officer_id
     *
     * @mbg.generated Tue Jun 12 17:12:11 CST 2018
     */
    public void setInsOfficerId(Long insOfficerId) {
        this.insOfficerId = insOfficerId;
    }
}